

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

beta_settings:
    # If using Cloud SQL, uncomment and set this value to the Cloud SQL
    # connection name, e.g.
    # You must also update the values in config.py.
    #
    cloud_sql_instances: "valid-progress-201319:us-central1:me"
